# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            otp
tagline:          'something'
description:      'a blog where I ramble about all sorts of things.'
url:              https://olliethepikachu.github.io
baseurl:          /

author:
  name:           'olliethepikachu'
  url:            https://github.com/ollietehpikachu

paginate:         5

# Custom vars
version:          1

github:
  repo:           https://github.com/olliethepikachu/olliethepikachu.github.io
